### ISSUE TITLE
vqa_tool: videollava or gpt-4v，除了这两种还可以用其他视频理解基座模型吗

### ISSUE THREAD

**Issue by NaLucia** [YueFan1014/VideoAgent#10]
问题同标题

**Comment by YueFan1014** [comment]
是的，你可以更改代码使用别的视频理解模型。不过我们的代码里目前只支持这两种模型。
Yes, of course. You can modify the code to try other video understanding models as vqa_tool. But our code only supports video-llava and gpt-4v for now.

**Comment by NaLucia** [comment]
谢谢大佬回复，可以帮忙指导下修改vqa_tool涉及哪些代码模块吗？

**Comment by YueFan1014** [comment]
可以更改tools.py中的[videollava_vqa](https://github.com/YueFan1014/VideoAgent/blob/21e4eb745b5ff4341f45170ddca02e0561ed088f/tools.py#L102)函数。该函数会被toolkit在[此处](https://github.com/YueFan1014/VideoAgent/blob/21e4eb745b5ff4341f45170ddca02e0561ed088f/tools.py#L213)调用。toolkit会被VideoAgent在[此处](https://github.com/YueFan1014/VideoAgent/blob/21e4eb745b5ff4341f45170ddca02e0561ed088f/main.py#L79)调用。

**Comment by NaLucia** [comment]
感谢大佬，我折腾一下
