### ISSUE TITLE
getting this error:

### ISSUE THREAD

**Issue by monjha** [YueFan1014/VideoAgent#2]
getting this error while running the default videos:
visual_question_answering(("how many boats are there in the video?", 0)) is not a valid tool, try one of [caption_retrieval, segment_localization, visual_question_answering, object_memory_qu
erying].

**Comment by YueFan1014** [comment]
Hi, it seems that the LLM does not call the tool in correct format. Please try other LLMs with stronger Instruction following ability (such as GPT-4-turbo). You can also run multiple times to answer the question.
