### ISSUE TITLE
An OSerror when run 'python video-llava.py'

### ISSUE THREAD

**Issue by yukio0321** [YueFan1014/VideoAgent#3]
OSError: It looks like the config file at 'cache_dir/models--LanguageBind--Video-LLaVA-7B/snapshots/aecae02b7dee5c249e096dcb0ce546eb6f811806/config.json' is not a valid JSON file.

**Comment by Cu2ta1n** [comment]
Have you resolved this issue? I might be facing a similar problem as you.

**Comment by yukio0321** [comment]
> Have you resolved this issue? I might be facing a similar problem as you.

The problem was resolved after I re-downloaded the file

**Comment by Cu2ta1n** [comment]
How do you call those models? Where did you modify it? I have never been able to call this local model properly, but when I re-download it from Hugging Face, I always encounter model mismatch issues.
