### ISSUE TITLE
How to Properly Install gensim==3.8.3 in a Python 3.9 Environment?

### ISSUE THREAD

**Issue by Khadgar123** [YueFan1014/VideoAgent#8]
I would like to know how to correctly install gensim==3.8.3 in a Python 3.9 environment to successfully install nlg-eval. Are there any specific dependencies or configurations that I should be aware of? Any advice or assistance would be greatly appreciated!

**Comment by Khadgar123** [comment]
Is nlg-eval only compatible with gensim==3.8.3? Are there any other versions of gensim that nlg-eval can work with?

**Comment by YueFan1014** [comment]
Hi, I have tested that gensim==3.8.3 is compatible with python 3.9.19.  I am using conda 24.1.2 on ubuntu 22.04.

**Comment by Khadgar123** [comment]
![2024-09-09_11-34](https://github.com/user-attachments/assets/231c64bc-0221-46ce-b726-1a4dfbf253d7)
I am using Ubuntu 22.04 with Python 3.9.19, and I am trying to install gensim version 3.8.3. Despite using the specified versions, the problem persists. Could you please provide any advice or solutions to resolve this issue?

**Comment by YueFan1014** [comment]
What is your gcc version? Mine is gcc 11.4.0

**Comment by Khadgar123** [comment]
![2024-09-09_14-09](https://github.com/user-attachments/assets/9eb558ad-8bdf-40ac-9e0c-741af82a2831)
Mine is  also gcc 11.4.0

**Comment by YueFan1014** [comment]
It seems that gensim==3.8.3 has the wheel for python 3.9. Maybe it is caused by the difference between conda and miniconda?
![Screenshot from 2024-09-09 14-32-08](https://github.com/user-attachments/assets/dbb6a601-adbe-4b74-ad13-65c308f1be93)

**Comment by tanghaom** [comment]
This is likely due to using NumPy version 2.0.
I first installed a 1.25 version of NumPy manually, and then installing gensim went smoothly.

**Comment by FFFFFFFANG1** [comment]
Hi, I faced the same trouble of builidng gensim, and all dependencies' versions are same as above. I also tried first installed numpy==1.25.0, but gensim can still not be built. But pip install gensim==3.18.2 works well, and I wonder if that version is compatible with 3.18.3.

**Comment by Khadgar123** [comment]
I later fixed the issue by using the command conda install gensim=3.8.3, and the installation was successful. It seems that only this version works.

**Comment by FFFFFFFANG1** [comment]
conda install gensim=3.8.3 works for me. Thanks.
